"""Getting the probe into a process that imports nothing of ours.

CPython's `site` module imports `sitecustomize` during startup, before the
script's own directory reaches `sys.path`. Putting a directory that contains
one on `PYTHONPATH` therefore runs our code first, in an application we never
touched — which is the whole trick behind zero-config instrumentation for
Textual.

Two properties are load-bearing, both measured on this machine and written up
in `docs/architecture/audit/textual.md`:

**We shadow whatever `sitecustomize` the environment already had.**
`PYTHONPATH` precedes `site-packages` and the stdlib, and `site` imports
exactly one `sitecustomize`. Homebrew's CPython ships one that reorders
`sys.path` and validates `PYTHONPATH` against the interpreter version, so
silently replacing it would change import semantics *only when instrumented* —
a bug that looks like it was caused by the tool and cannot be reproduced
without it. The generated module therefore removes its own directory from
`sys.path` and re-imports, running the module it displaced before doing
anything of its own.

**Nothing is written into the project, and ownership is one-shot.** The
directory is temporary and is named only in the launched environment. The
first application interpreter atomically claims it, captures the semantic
credentials process-locally, and scrubs both credentials and our path before
the application's first line. Python children therefore cannot attach to the
parent's semantic endpoint even when they inherit the parent's environment.

Where it does not reach, measured: `python -S` (no `site`, so no
`sitecustomize` at all) and `python -E` (ignores `PYTHONPATH`). Both are
deliberate opt-outs by the person running the interpreter. `poetry run` is a
special two-interpreter path: a one-hop marker makes the Poetry console process
pass ownership to the application interpreter it launches.
"""

from __future__ import annotations

import os
import shutil
import tempfile
from typing import Dict, List, Mapping, Optional, Sequence, Tuple

#: Environment variables that switch instrumentation on. Kept as literals
#: rather than imported from `termwright`: the generated `sitecustomize` runs
#: before anything of ours is importable, so it cannot rely on our package
#: being on the path yet.
ENV_ENDPOINT = "TERMWRIGHT_ENDPOINT"
ENV_TOKEN = "TERMWRIGHT_TOKEN"
ENV_OWNER = "TERMWRIGHT_PYTHON_OWNER"
ENV_PASSTHROUGH = "TERMWRIGHT_PYTHON_PASSTHROUGH"

#: Name of the file CPython looks for. Not ours to choose.
SITECUSTOMIZE = "sitecustomize.py"


def is_instrumented(env: Mapping[str, str]) -> bool:
    """Whether this environment asks for instrumentation.

    The dormant rule: without both variables the probe installs nothing at
    all. The launcher already knows not to inject in that case; the generated
    module checks again, for a `PYTHONPATH` that outlived the run it was
    written for.
    """
    return bool(env.get(ENV_ENDPOINT)) and bool(env.get(ENV_TOKEN))


def sitecustomize_source(*, package_root: str) -> str:
    """The text of the `sitecustomize.py` we generate.

    `package_root` is prepended to `sys.path` so the generated module can
    import `termwright_probe` even when the probe is not installed in the
    target's environment — an application under test has no reason to have our
    package, and requiring it would be configuration by another name.
    """
    return f'''"""Generated by termwright. Ephemeral: delete this directory freely.

CPython imports this file during startup because its directory is on
PYTHONPATH. Everything here runs before the application's first line.
"""

import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))


def _path_key(path: str) -> str:
    """Compare inherited paths with Windows case semantics."""
    return os.path.normcase(os.path.abspath(path or "."))


def _is_poetry_launcher() -> bool:
    """Let Poetry pass the bootstrap to the interpreter it launches."""
    name = os.path.basename(sys.argv[0]).lower()
    marked = os.environ.pop({ENV_PASSTHROUGH!r}, None) == "poetry"
    return marked and (name == "poetry" or name == "poetry.exe")


def _claim() -> bool:
    """Atomically make this interpreter the sole owner of this bootstrap."""
    owner = os.environ.get({ENV_OWNER!r})
    if not owner:
        return False
    flags = os.O_CREAT | os.O_EXCL | os.O_WRONLY
    flags |= getattr(os, "O_CLOEXEC", 0)
    flags |= getattr(os, "O_NOFOLLOW", 0)
    try:
        descriptor = os.open(owner, flags, 0o600)
    except FileExistsError:
        return False
    except OSError:
        return False
    try:
        os.write(descriptor, str(os.getpid()).encode("ascii"))
    finally:
        os.close(descriptor)
    return True


def _scrub() -> None:
    """Keep secrets and bootstrap code out of descendant environments."""
    os.environ.pop({ENV_ENDPOINT!r}, None)
    os.environ.pop({ENV_TOKEN!r}, None)
    os.environ.pop({ENV_OWNER!r}, None)
    entries = os.environ.get("PYTHONPATH", "").split(os.pathsep)
    remaining = [
        entry for entry in entries
        if entry and _path_key(entry) != _path_key(_HERE)
    ]
    if remaining:
        os.environ["PYTHONPATH"] = os.pathsep.join(remaining)
    else:
        os.environ.pop("PYTHONPATH", None)


def _chain() -> None:
    """Run the sitecustomize this one displaced, if there is one.

    Homebrew's CPython ships a sitecustomize that reorders sys.path. Shadowing
    it silently would change import semantics under instrumentation only, so
    the displaced module runs first and its effects are in place before the
    probe installs anything.
    """
    remaining = [entry for entry in sys.path if _path_key(entry) != _path_key(_HERE)]
    if len(remaining) == len(sys.path):
        return
    ours = sys.modules.pop("sitecustomize", None)
    saved = list(sys.path)
    sys.path[:] = remaining
    try:
        import sitecustomize  # noqa: F401  the displaced one
    except Exception:
        # A broken neighbour is not ours to fix, and it must not stop the
        # application from starting.
        pass
    finally:
        sys.path[:] = saved
        if ours is not None:
            sys.modules["sitecustomize"] = ours


def _install() -> None:
    if not (os.environ.get({ENV_ENDPOINT!r}) and os.environ.get({ENV_TOKEN!r})):
        # Dormant: a PYTHONPATH that outlived its run installs nothing.
        return
    # Poetry is a Python console script but not the application process. It
    # must hand the still-unclaimed bootstrap to `poetry run`'s interpreter.
    if _is_poetry_launcher():
        return
    claimed = _claim()
    captured = dict(os.environ) if claimed else None
    root = {package_root!r}
    try:
        if not claimed:
            return
        if root not in sys.path:
            sys.path.insert(0, root)
        try:
            from termwright_probe import install
        except Exception:
            # The probe is unreachable or broken. The application is not ours
            # to take down over it, and there is no terminal to complain to.
            return
        install(env=captured)
    finally:
        # This interpreter keeps a private copy; every subprocess sees a
        # dormant environment and cannot race or reuse the parent's channel.
        _scrub()


_chain()
_install()
'''


class Bootstrap:
    """A temporary directory holding the generated `sitecustomize.py`.

    Usable as a context manager, which is how tests and short-lived launchers
    should take it. A driver that outlives the call site keeps the object and
    calls :meth:`cleanup` when the session ends.
    """

    def __init__(self, directory: str) -> None:
        self.directory = directory

    @property
    def sitecustomize(self) -> str:
        """Full path of the generated file."""
        return os.path.join(self.directory, SITECUSTOMIZE)

    @property
    def owner(self) -> str:
        """Path atomically claimed by the one application interpreter."""
        return os.path.join(self.directory, "owner")

    def env(self, base: Optional[Mapping[str, str]] = None) -> Dict[str, str]:
        """`base` with our directory prepended to `PYTHONPATH`.

        Prepended, not replaced: an application that relies on its own
        `PYTHONPATH` keeps it. Ours goes first because `site` imports the first
        `sitecustomize` it finds, and being displaced would mean instrumenting
        nothing.
        """
        env = dict(os.environ if base is None else base)
        existing = env.get("PYTHONPATH", "")
        env["PYTHONPATH"] = (
            self.directory if not existing else self.directory + os.pathsep + existing
        )
        env[ENV_OWNER] = self.owner
        return env

    def cleanup(self) -> None:
        """Remove the directory. Safe to call more than once."""
        shutil.rmtree(self.directory, ignore_errors=True)

    def __enter__(self) -> "Bootstrap":
        return self

    def __exit__(self, *exc: object) -> None:
        self.cleanup()


def write_bootstrap(*, package_root: Optional[str] = None) -> Bootstrap:
    """Create the ephemeral directory and write the generated module into it.

    :param package_root: Directory containing `termwright_probe`. Defaults to
        the one this module was imported from, which is what a launcher
        running out of an installed package wants.
    """
    if package_root is None:
        package_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    directory = tempfile.mkdtemp(prefix="termwright-probe-")
    bootstrap = Bootstrap(directory)
    with open(bootstrap.sitecustomize, "w", encoding="utf-8") as handle:
        handle.write(sitecustomize_source(package_root=package_root))
    return bootstrap


def with_probe(
    argv: Sequence[str],
    *,
    env: Optional[Mapping[str, str]] = None,
) -> Tuple[List[str], Dict[str, str], Optional[Bootstrap]]:
    """Compose the command and environment that run `argv` instrumented.

    Returns the command unchanged — Python needs no extra flag, only the
    variable — together with the environment to run it in and the
    :class:`Bootstrap` whose directory must outlive the process.

    Without instrumentation in `env` the third element is ``None`` and the
    environment comes back untouched: no directory is created, nothing is
    written, and the command is exactly what the caller passed.
    """
    source: Mapping[str, str] = os.environ if env is None else env
    if not is_instrumented(source):
        return list(argv), dict(source), None
    bootstrap = write_bootstrap()
    composed = bootstrap.env(source)
    executable = os.path.basename(argv[0]).lower() if argv else ""
    if (
        executable in ("poetry", "poetry.exe")
        and "run" in argv[1:]
    ):
        # Poetry is itself a Python console script. Its sitecustomize consumes
        # this one-hop marker, leaving the actual `poetry run` interpreter to
        # atomically claim the bootstrap.
        composed[ENV_PASSTHROUGH] = "poetry"
    return list(argv), composed, bootstrap
