/**
 * The ephemeral Go workspace that points a build at our instrumented copy.
 *
 * The whole zero-config promise for Go rests on one property: a `go.work` file
 * outside the project can redirect a dependency without the project knowing.
 * `GOWORK=<file> go build` then compiles our copy, while the project's
 * `go.mod`, `go.sum` and any `go.work` of its own stay byte-identical.
 *
 * Two facts from the Phase 0 audit shape this file, both measured rather than
 * assumed (`docs/architecture/audit/tview.md` §6):
 *
 * - A generated workspace that lists only the target module **breaks a
 *   multi-module project**: dropping the project's own `use` lines sends Go to
 *   the network for a module that exists only on disk. The generator therefore
 *   inherits the existing workspace instead of inventing one.
 * - `GOWORK` beats both a discovered `go.work` and a `replace` in the user's
 *   `go.mod`, so the redirect is reliable — and correspondingly easy to apply
 *   by accident, which is why the canary in `canaryCheck` exists.
 */

import { execFile } from 'node:child_process';
import { access, mkdir, readFile, realpath, stat, writeFile } from 'node:fs/promises';
import { devNull } from 'node:os';
import { dirname, isAbsolute, join, resolve } from 'node:path';
import { promisify } from 'node:util';

const run = promisify(execFile);

/** One `use` entry of a Go workspace, as an absolute directory. */
export interface WorkspaceUse {
  readonly dir: string;
  /**
   * Module path declared in that directory's go.mod, when known.
   *
   * Needed because Go refuses a workspace that both uses and replaces the same
   * module, and the two are matched by module path rather than by directory:
   * a replace pointing *at* a used directory for some other module path is
   * legal and must not be disturbed.
   */
  readonly module?: string;
}

/** One `replace` entry: a module path redirected to a directory or a version. */
export interface WorkspaceReplace {
  readonly from: string;
  /** Absolute directory. Version replacements are not generated by us. */
  readonly to: string;
  /** Optional exact version. Versioned replacements may coexist with a `use`. */
  readonly version?: string;
}

/** The parts of an existing workspace we must carry across. */
export interface InheritedWorkspace {
  /** The `go` directive, or undefined when there was no workspace to inherit. */
  readonly goVersion?: string;
  readonly uses: readonly WorkspaceUse[];
  readonly replaces: readonly WorkspaceReplace[];
}

/** Raw shape of `go work edit -json`; only the fields we consume. */
interface GoWorkJson {
  readonly Go?: string;
  readonly Use?: readonly { readonly DiskPath?: string }[] | null;
  readonly Replace?:
    | readonly {
        readonly Old?: { readonly Path?: string };
        readonly New?: { readonly Path?: string; readonly Version?: string };
      }[]
    | null;
}

/**
 * Thrown for conditions a user must fix, rather than ones we can work around.
 *
 * `vendor-mode` is the one the audit called out: `-mod=vendor` is incompatible
 * with workspace mode, so silently overriding it would change what the build
 * compiles behind the user's back.
 */
export class WorkspaceError extends Error {
  constructor(
    readonly code: 'vendor-mode' | 'go-missing' | 'workspace-unreadable',
    message: string,
  ) {
    super(message);
    this.name = 'WorkspaceError';
  }
}

/**
 * Refuses a build that asks for vendor mode.
 *
 * Checked against the environment the child will actually get, not
 * `process.env`, because a launcher composes that environment itself.
 */
export function assertNoVendorMode(env: NodeJS.ProcessEnv): void {
  const flags = env['GOFLAGS'];
  if (flags === undefined) return;
  if (!/(^|\s)-mod=vendor(\s|$)/u.test(flags)) return;
  throw new WorkspaceError(
    'vendor-mode',
    'GOFLAGS contains -mod=vendor, which Go refuses to combine with workspace mode. ' +
      'termwright would have to override it to instrument this build, which would change ' +
      'what gets compiled. Remove -mod=vendor from GOFLAGS, or run the tests without the probe.',
  );
}

/** Refuses both explicitly configured and Go's automatic module vendor mode. */
export async function assertNoEffectiveVendorMode(
  dir: string,
  env: NodeJS.ProcessEnv,
): Promise<void> {
  assertNoVendorMode(env);
  let settings: { GOFLAGS?: string; GOMOD?: string; GOWORK?: string };
  try {
    const { stdout } = await run('go', ['env', '-json', 'GOFLAGS', 'GOMOD', 'GOWORK'], {
      cwd: dir,
      env,
    });
    settings = JSON.parse(stdout) as { GOFLAGS?: string; GOMOD?: string; GOWORK?: string };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    if (/ENOENT/u.test(message)) {
      throw new WorkspaceError('go-missing', 'the `go` toolchain is not on PATH');
    }
    throw new WorkspaceError('workspace-unreadable', `go env failed: ${message}`);
  }
  assertNoVendorMode({ GOFLAGS: settings.GOFLAGS });
  if (/(^|\s)-mod=(?:mod|readonly)(\s|$)/u.test(settings.GOFLAGS ?? '')) return;

  let workspaceFile = settings.GOWORK?.trim() ?? '';
  if ((workspaceFile === '' || workspaceFile === 'off') && env['GOWORK'] !== 'off') {
    workspaceFile = (await findWorkspaceFromEntryPath(dir)) ?? workspaceFile;
  }
  const workspaceMode = workspaceFile !== '' && workspaceFile !== 'off';
  const sourceFile = workspaceMode ? workspaceFile : settings.GOMOD;
  if (sourceFile === undefined || sourceFile === '' || sourceFile === devNull) return;
  let source: string;
  try {
    source = await readFile(sourceFile, 'utf8');
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new WorkspaceError('workspace-unreadable', `cannot read ${sourceFile}: ${message}`);
  }
  if (!goVersionAtLeast(source, 14)) return;
  const vendorDir = join(dirname(sourceFile), 'vendor');
  try {
    if (!(await stat(vendorDir)).isDirectory()) return;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return;
    const message = error instanceof Error ? error.message : String(error);
    throw new WorkspaceError('workspace-unreadable', `cannot inspect ${vendorDir}: ${message}`);
  }
  const vendoredWorkspace = await modulesTextIsForWorkspace(vendorDir);
  if (vendoredWorkspace !== workspaceMode) return;
  throw new WorkspaceError(
    'vendor-mode',
    `${workspaceMode ? 'this workspace' : 'this module'} has a vendor directory and its go ` +
      'directive enables automatic vendor mode. ' +
      'Termwright cannot combine that dependency graph with the generated instrumentation ' +
      'workspace without changing what gets compiled. Build without vendoring, explicitly ' +
      'select -mod=mod, or run the tests without the probe.',
  );
}

async function modulesTextIsForWorkspace(vendorDir: string): Promise<boolean> {
  try {
    const source = await readFile(join(vendorDir, 'modules.txt'), 'utf8');
    const firstLine = source.split(/\r?\n/u, 1)[0] ?? '';
    if (!firstLine.startsWith('## ')) return false;
    return firstLine
      .slice(3)
      .split(';')
      .some((annotation) => annotation.trim() === 'workspace');
  } catch (error) {
    const code = (error as NodeJS.ErrnoException).code;
    if (code === 'ENOENT') return false;
    const message = error instanceof Error ? error.message : String(error);
    throw new WorkspaceError(
      'workspace-unreadable',
      `cannot inspect vendor/modules.txt: ${message}`,
    );
  }
}

function goVersionAtLeast(source: string, minimumMinor: number): boolean {
  const version = /^go\s+(\d+)\.(\d+)/mu.exec(source);
  if (version === null) return false;
  const major = Number(version[1]);
  const minor = Number(version[2]);
  return major > 1 || (major === 1 && minor >= minimumMinor);
}

/**
 * Reads the workspace that already applies in `dir`, if any.
 *
 * Uses `go work edit -json` rather than parsing the file: the format is
 * Go's to change, and the JSON is the supported way to read it. A project
 * without a workspace is the common case and is not an error — it comes back
 * with no uses, and the caller adds the module itself.
 */
export async function readWorkspace(
  dir: string,
  env: NodeJS.ProcessEnv = process.env,
): Promise<InheritedWorkspace> {
  // `go env GOWORK` answers both questions at once: whether a workspace applies
  // here, and where its file is. The second matters because `DiskPath` entries
  // are relative to the *workspace file*, not to the directory we ran in —
  // resolving them against the cwd yields `…/app/app` and a build that cannot
  // find its own modules.
  let workspaceFile: string;
  try {
    const { stdout } = await run('go', ['env', 'GOWORK'], { cwd: dir, env });
    workspaceFile = stdout.trim();
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    if (/ENOENT/u.test(message)) {
      throw new WorkspaceError('go-missing', 'the `go` toolchain is not on PATH');
    }
    throw new WorkspaceError('workspace-unreadable', `go env GOWORK failed: ${message}`);
  }

  // `chdir` resolves symlinks before Go discovers parent workspaces. Preserve
  // the caller's lexical entry path when it sits inside a go.work tree.
  if ((workspaceFile === '' || workspaceFile === 'off') && env['GOWORK'] !== 'off') {
    workspaceFile = (await findWorkspaceFromEntryPath(dir)) ?? workspaceFile;
  }

  // A project without a workspace is the common case, not an error.
  if (workspaceFile === '' || workspaceFile === 'off') return { uses: [], replaces: [] };

  const base = dirname(workspaceFile);

  let stdout: string;
  try {
    ({ stdout } = await run('go', ['work', 'edit', '-json'], {
      cwd: dir,
      env: { ...env, GOWORK: workspaceFile },
    }));
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new WorkspaceError('workspace-unreadable', `go work edit -json failed: ${message}`);
  }

  let parsed: GoWorkJson;
  try {
    parsed = JSON.parse(stdout) as GoWorkJson;
  } catch {
    throw new WorkspaceError('workspace-unreadable', 'go work edit -json returned invalid JSON');
  }

  // Resolved against the workspace file's directory, and absolute in the
  // output, because the generated file lives somewhere else entirely.
  const usePaths = (parsed.Use ?? [])
    .map((entry) => entry.DiskPath)
    .filter((path): path is string => path !== undefined)
    .map((path) => (isAbsolute(path) ? path : resolve(base, path)));
  let uses: WorkspaceUse[];
  try {
    uses = await Promise.all(usePaths.map(async (path) => ({ dir: await realpath(path) })));
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new WorkspaceError(
      'workspace-unreadable',
      `go.work contains a use path that cannot be resolved: ${message}`,
    );
  }

  const replaces = (parsed.Replace ?? [])
    .map((entry) => ({ from: entry.Old?.Path, to: entry.New?.Path, version: entry.New?.Version }))
    .filter(
      (entry): entry is { from: string; to: string; version: undefined } =>
        entry.from !== undefined && entry.to !== undefined && entry.version === undefined,
    )
    .map((entry) => ({
      from: entry.from,
      to: isAbsolute(entry.to) ? entry.to : resolve(base, entry.to),
    }));

  return { ...(parsed.Go === undefined ? {} : { goVersion: parsed.Go }), uses, replaces };
}

async function findWorkspaceFromEntryPath(dir: string): Promise<string | null> {
  let current = resolve(dir);
  for (;;) {
    const candidate = join(current, 'go.work');
    try {
      await access(candidate);
      return candidate;
    } catch (error) {
      const code = (error as NodeJS.ErrnoException).code;
      if (code !== 'ENOENT' && code !== 'ENOTDIR') {
        const message = error instanceof Error ? error.message : String(error);
        throw new WorkspaceError(
          'workspace-unreadable',
          `cannot inspect lexical workspace candidate ${candidate}: ${message}`,
        );
      }
      const parent = dirname(current);
      if (parent === current) return null;
      current = parent;
    }
  }
}

/** What the generated workspace must contain. */
export interface WorkspacePlan {
  /** The module being built, so it is used even when the project has no workspace. */
  readonly moduleDir: string;
  readonly inherited: InheritedWorkspace;
  /**
   * Local modules supplied as workspace members. Unlike a filesystem replace,
   * a member contributes its own dependency graph on every target OS. This is
   * required for the protocol client: its Windows-only pipe dependency is not
   * selected when the client is merely a replaced, pruned dependency.
   */
  readonly suppliedUses?: readonly WorkspaceUse[];
  /**
   * Our redirects. This always includes framework → instrumented copy. A
   * supplied module may additionally need exact-version redirects when a
   * project explicitly requires it; those legally coexist with `suppliedUses`.
   */
  readonly replaces: readonly WorkspaceReplace[];
  /** Used when neither the inherited workspace nor the caller says otherwise. */
  readonly fallbackGoVersion?: string;
}

/**
 * Renders the workspace file.
 *
 * Kept separate from writing it so the result can be asserted directly — the
 * failure this guards against (a dropped `use` line) is invisible until a
 * multi-module project builds, which is an expensive test to run for every
 * change.
 */
export function renderWorkspace(plan: WorkspacePlan): string {
  // The highest wins, not the inherited one: a project whose workspace says
  // 1.22 while a member needs 1.25 must still get a workspace that builds.
  const goVersion = highest(plan.inherited.goVersion, plan.fallbackGoVersion) ?? '1.22';

  // A module cannot be both used and replaced at all versions. An exact-version
  // replacement is legal and is needed when another workspace module carries
  // an explicit require for the local module.
  const replacedModules = new Set(
    plan.replaces.filter((entry) => entry.version === undefined).map((entry) => entry.from),
  );
  const uses = [...plan.inherited.uses, ...(plan.suppliedUses ?? [])]
    .filter((entry) => entry.module === undefined || !replacedModules.has(entry.module))
    .map((entry) => entry.dir);
  if (!uses.includes(plan.moduleDir)) uses.push(plan.moduleDir);

  // The user's own replace of a module we redirect would fight ours; ours is
  // the point of the exercise, so theirs is dropped and the rest carried over.
  const ours = new Set(plan.replaces.map((entry) => entry.from));
  const replaces = plan.inherited.replaces.filter((entry) => !ours.has(entry.from));

  const lines = [
    '// Generated by termwright. Ephemeral: nothing reads this but one build.',
    `go ${goVersion}`,
    '',
    ...uses.map((dir) => `use ${quote(dir)}`),
    '',
    ...replaces.map((entry) => `replace ${entry.from} => ${quote(entry.to)}`),
    ...plan.replaces.map(
      (entry) =>
        `replace ${entry.from}${entry.version === undefined ? '' : ` ${entry.version}`} => ${quote(entry.to)}`,
    ),
    '',
  ];
  return lines.join('\n');
}

/** Module path declared in a directory's go.mod, when there is one. */
async function moduleNameIn(dir: string): Promise<string | undefined> {
  const { readFile } = await import('node:fs/promises');
  try {
    const text = await readFile(join(dir, 'go.mod'), 'utf8');
    return /^module\s+(\S+)\s*$/mu.exec(text)?.[1];
  } catch {
    return undefined;
  }
}

/** The newer of two `go` directives, tolerating either being absent. */
function highest(left: string | undefined, right: string | undefined): string | undefined {
  if (left === undefined) return right;
  if (right === undefined) return left;
  return compareGoVersions(left, right) >= 0 ? left : right;
}

/** Go's workspace syntax takes a quoted string for any path with spaces. */
function quote(path: string): string {
  return /[\s"]/u.test(path) ? JSON.stringify(path) : path;
}

/**
 * Writes the rendered workspace and returns the path to hand to `GOWORK`.
 *
 * Every directory is canonicalised first. Go reports and compares module
 * directories after resolving symlinks, so a caller that passes the symlinked
 * form — `/var/folders/…` on macOS, where `/var` links to `/private/var` — would
 * produce a file whose `use` lines Go does not recognise as the directory it is
 * building in: *directory prefix . does not contain modules listed in go.work*.
 * Canonicalising here means no caller has to know that.
 */
export async function writeWorkspace(file: string, plan: WorkspacePlan): Promise<string> {
  const computed =
    plan.fallbackGoVersion ??
    (await highestGoDirective([
      plan.moduleDir,
      ...plan.inherited.uses.map((use) => use.dir),
      ...(plan.suppliedUses ?? []).map((use) => use.dir),
      ...plan.replaces.map((replace) => replace.to),
    ]));

  const canonical: WorkspacePlan = {
    ...plan,
    // Computed rather than defaulted. A workspace whose `go` line is older
    // than any member's refuses the build outright — "module . listed in
    // go.work file requires go >= 1.25.0, but go.work lists go 1.24" — and a
    // hardcoded floor turns every modern framework into that error.
    ...(computed === undefined ? {} : { fallbackGoVersion: computed }),
    moduleDir: await realDir(plan.moduleDir),
    inherited: {
      ...plan.inherited,
      uses: await Promise.all(
        plan.inherited.uses.map(async (use) => {
          const dir = await realDir(use.dir);
          const module = use.module ?? (await moduleNameIn(dir));
          return module === undefined ? { dir } : { dir, module };
        }),
      ),
      replaces: await Promise.all(
        plan.inherited.replaces.map(async (r) => ({ from: r.from, to: await realDir(r.to) })),
      ),
    },
    replaces: await Promise.all(
      plan.replaces.map(async (r) => ({
        from: r.from,
        to: await realDir(r.to),
        ...(r.version === undefined ? {} : { version: r.version }),
      })),
    ),
    suppliedUses: await Promise.all(
      (plan.suppliedUses ?? []).map(async (use) => {
        const dir = await realDir(use.dir);
        const module = use.module ?? (await moduleNameIn(dir));
        return module === undefined ? { dir } : { dir, module };
      }),
    ),
  };

  await mkdir(dirname(file), { recursive: true });
  await writeFile(file, renderWorkspace(canonical), 'utf8');
  return file;
}

/**
 * The newest `go` directive among a set of modules.
 *
 * The workspace has to be at least as new as everything in it. Reading the
 * files is cheap and exact; inferring from the toolchain is neither, because
 * the toolchain may be newer than the modules and the workspace would then
 * claim a version nothing needs.
 */
async function highestGoDirective(dirs: readonly string[]): Promise<string | undefined> {
  const { readFile } = await import('node:fs/promises');
  let best: string | undefined;

  for (const dir of dirs) {
    let text: string;
    try {
      text = await readFile(join(dir, 'go.mod'), 'utf8');
    } catch {
      continue;
    }
    const match = /^go\s+(\d+\.\d+(?:\.\d+)?)\s*$/mu.exec(text);
    if (match?.[1] === undefined) continue;
    if (best === undefined || compareGoVersions(match[1], best) > 0) best = match[1];
  }
  return best;
}

/** Orders two `go` directives numerically, so 1.10 beats 1.9. */
function compareGoVersions(left: string, right: string): number {
  const a = left.split('.').map(Number);
  const b = right.split('.').map(Number);
  for (let index = 0; index < Math.max(a.length, b.length); index += 1) {
    const difference = (a[index] ?? 0) - (b[index] ?? 0);
    if (difference !== 0) return difference;
  }
  return 0;
}

/** Resolves symlinks, leaving a path that does not exist yet untouched. */
async function realDir(dir: string): Promise<string> {
  const { realpath } = await import('node:fs/promises');
  try {
    return await realpath(dir);
  } catch {
    return dir;
  }
}

/**
 * Proves that a build really compiled our copy rather than the module cache.
 *
 * The check is deliberately crude and deliberately permanent. A redirect that
 * silently stops applying — a cache key that changed, a `GOWORK` a wrapper
 * dropped, a toolchain that ignored the file — produces a build that passes
 * every test while reporting no semantics at all, which is the single most
 * expensive failure this package can have. Compiling a file that cannot
 * compile turns it into an immediate, named error.
 *
 * @param copyDir - the instrumented copy; a temporary file is written into it.
 * @param moduleDir - a module that imports the framework.
 * @param workspaceFile - the generated workspace.
 * @returns the compiler's message, which must name the file inside `copyDir`.
 */
export async function canaryCheck(options: {
  readonly copyDir: string;
  readonly moduleDir: string;
  readonly workspaceFile: string;
  readonly packageName: string;
  readonly env?: NodeJS.ProcessEnv;
}): Promise<{ readonly proved: boolean; readonly detail: string }> {
  const marker = join(options.copyDir, 'termwright_canary.go');
  await writeFile(
    marker,
    `package ${options.packageName}\n\n` +
      '// Written by termwright, deleted immediately: a build that does not fail\n' +
      '// here is not compiling this copy.\n' +
      'func init() { _ = termwrightCanaryUndefinedOnPurpose }\n',
    'utf8',
  );

  try {
    await run('go', ['build', './...'], {
      cwd: options.moduleDir,
      env: { ...(options.env ?? process.env), GOWORK: options.workspaceFile },
    });
    return {
      proved: false,
      detail:
        'the build succeeded with a deliberately broken file in the instrumented copy, ' +
        'so the copy is not what was compiled',
    };
  } catch (error) {
    const detail = error instanceof Error ? error.message : String(error);
    return {
      proved: detail.includes('termwrightCanaryUndefinedOnPurpose'),
      detail,
    };
  } finally {
    const { rm } = await import('node:fs/promises');
    await rm(marker, { force: true });
  }
}
