/**
 * Codegen: a recorded interaction becomes a `@termwright/test` file.
 *
 * The recorder produces {@link RecordedEvent}s — semantic actions where it can
 * (a click on a node the inspector identified), decoded key actions where it
 * cannot. This module turns that list into source. It is deliberately dumb:
 * one event, one statement, in order. Everything clever (choosing the narrowest
 * selector, deciding a keypress was really a paste) happened upstream, where the
 * semantic tree was still around to decide with.
 *
 * @packageDocumentation
 */

import { quote, type GeneratedSelector } from './selector.js';

/** One recorded interaction, in recording order. */
export type RecordedEvent =
  | {
      readonly kind: 'launch';
      readonly command: readonly string[];
      readonly columns?: number;
      readonly rows?: number;
      readonly t: number;
    }
  | { readonly kind: 'press'; readonly keys: string; readonly t: number }
  | { readonly kind: 'type'; readonly text: string; readonly t: number }
  | { readonly kind: 'paste'; readonly text: string; readonly t: number }
  | { readonly kind: 'raw'; readonly dataB64: string; readonly t: number }
  | {
      readonly kind: 'withheld-input';
      readonly inputKind: 'type' | 'paste' | 'raw';
      readonly bytes: number;
      readonly t: number;
    }
  | { readonly kind: 'click'; readonly selector: GeneratedSelector; readonly t: number }
  | { readonly kind: 'assert-snapshot'; readonly t: number }
  | { readonly kind: 'assert-visible'; readonly selector: GeneratedSelector; readonly t: number }
  | { readonly kind: 'assert-text'; readonly text: string; readonly t: number }
  | { readonly kind: 'wait-text'; readonly text: string; readonly t: number }
  | { readonly kind: 'step'; readonly title: string; readonly t: number };

/** Options for {@link generateTestSource}. */
export interface CodegenOptions {
  /** Test title. Default `recorded session`. */
  readonly testName?: string;
  /** Variable the launched session is bound to. Default `app`. */
  readonly variable?: string;
  /** Module the preset is imported from. Default `@termwright/test`. */
  readonly importFrom?: string;
}

/**
 * Renders recorded events as the source of a test file.
 *
 * Steps recorded with the "step" button wrap the actions that follow them, up to
 * the next step, in `test.step()` — the same grouping the trace and the HTML
 * report use.
 *
 * @example
 * ```ts
 * generateTestSource([
 *   { kind: 'launch', command: ['node', 'app.js'], t: 0 },
 *   { kind: 'click', selector, t: 120 },
 * ]);
 * ```
 */
export function generateTestSource(
  events: readonly RecordedEvent[],
  options: CodegenOptions = {},
): string {
  const variable = options.variable ?? 'app';
  const testName = options.testName ?? 'recorded session';
  const importFrom = options.importFrom ?? '@termwright/test';
  const usesExpect = events.some((event) => event.kind.startsWith('assert-'));
  const usesStep = events.some((event) => event.kind === 'step');

  const imports = usesExpect ? 'expect, test' : 'test';
  const fixtures = usesStep ? '{ terminal, step }' : '{ terminal }';

  const lines: string[] = [
    '// Generated by `termwright ui` (recorder). Review before committing:',
    '// generated selectors are the narrowest ones the tree allowed, not',
    '// necessarily the ones that describe your intent.',
    '',
    `import { ${imports} } from ${quote(importFrom)};`,
    '',
    `test(${quote(testName)}, async (${fixtures}) => {`,
  ];

  const body = renderBody(events, variable);
  for (const line of body) lines.push(line === '' ? '' : `  ${line}`);
  lines.push('});', '');
  return lines.join('\n');
}

function renderBody(events: readonly RecordedEvent[], variable: string): string[] {
  const lines: string[] = [];
  let launched = false;
  let openStep: { title: string; lines: string[] } | undefined;

  const emit = (line: string): void => {
    if (openStep === undefined) lines.push(line);
    else openStep.lines.push(line);
  };
  const closeStep = (): void => {
    if (openStep === undefined) return;
    lines.push(`await step(${quote(openStep.title)}, async () => {`);
    for (const line of openStep.lines) lines.push(line === '' ? '' : `  ${line}`);
    lines.push('});');
    openStep = undefined;
  };

  for (const event of events) {
    switch (event.kind) {
      case 'launch': {
        closeStep();
        const parts = [`command: [${event.command.map(quote).join(', ')}]`];
        if (event.columns !== undefined) parts.push(`columns: ${event.columns}`);
        if (event.rows !== undefined) parts.push(`rows: ${event.rows}`);
        lines.push(`const ${variable} = await terminal.launch({ ${parts.join(', ')} });`);
        lines.push('');
        launched = true;
        break;
      }
      case 'step':
        closeStep();
        if (lines.length > 0 && lines[lines.length - 1] !== '') lines.push('');
        openStep = { title: event.title, lines: [] };
        break;
      case 'press':
        emit(`await ${variable}.press(${quote(event.keys)});`);
        break;
      case 'type':
        emit(`await ${variable}.type(${quote(event.text)});`);
        break;
      case 'paste':
        emit(`await ${variable}.paste(${quote(event.text)});`);
        break;
      case 'raw':
        emit(`await ${variable}.write(Buffer.from(${quote(event.dataB64)}, 'base64'));`);
        break;
      case 'withheld-input':
        emit(
          `// TODO: ${event.inputKind} input withheld by recorder policy (${event.bytes} bytes).`,
        );
        break;
      case 'click':
        emit(`await ${event.selector.expression}.click();`);
        break;
      case 'wait-text':
        emit(`await ${variable}.waitForText(${quote(event.text)});`);
        break;
      case 'assert-visible':
        emit(`await expect(${event.selector.expression}).toBeVisible();`);
        break;
      case 'assert-text':
        emit(`await expect(${variable}).toHaveText(${quote(event.text)});`);
        break;
      case 'assert-snapshot':
        // No inline expectation: the preset writes the YAML snapshot file on
        // the first run, which is also the form a reviewer reads.
        emit(`await expect(${variable}).toMatchSemanticSnapshot();`);
        break;
    }
  }
  closeStep();
  if (!launched) {
    lines.unshift(
      `const ${variable} = await terminal.launch({ command: ['echo', 'set a command'] });`,
      '',
    );
  }
  while (lines.length > 0 && lines[lines.length - 1] === '') lines.pop();
  return lines;
}
