import { describe, expect, it } from 'vitest';
import { node, snapshot } from './__fixtures__/fake-session.js';
import { generateTestSource, type RecordedEvent } from './codegen.js';
import { generateSelector, type GeneratedSelector } from './selector.js';

const tree = snapshot(1, [
  node({ id: 'd1', role: 'dialog', name: 'Permission', state: { modal: true } }),
  node({ id: 'b1', role: 'button', name: 'Approve', parentId: 'd1' }),
  node({ id: 'b2', role: 'button', name: 'Reject', parentId: 'd1' }),
]);

const selector = (id: string): GeneratedSelector => {
  const generated = generateSelector(tree, id, { root: 'app' });
  if (generated === undefined) throw new Error(`no selector for ${id}`);
  return generated;
};

describe('generateTestSource', () => {
  it('generates a runnable test from a recorded session', () => {
    const events: RecordedEvent[] = [
      { kind: 'launch', command: ['node', 'agent.js'], columns: 100, rows: 30, t: 0 },
      { kind: 'wait-text', text: 'Permission required', t: 40 },
      { kind: 'click', selector: selector('b1'), t: 120 },
      { kind: 'type', text: 'ls -la', t: 200 },
      { kind: 'press', keys: 'Enter', t: 260 },
      { kind: 'assert-snapshot', t: 300 },
    ];

    expect(generateTestSource(events, { testName: 'approves the command' })).toBe(
      `// Generated by \`termwright ui\` (recorder). Review before committing:
// generated selectors are the narrowest ones the tree allowed, not
// necessarily the ones that describe your intent.

import { expect, test } from '@termwright/test';

test('approves the command', async ({ terminal }) => {
  const app = await terminal.launch({ command: ['node', 'agent.js'], columns: 100, rows: 30 });

  await app.waitForText('Permission required');
  await app.getByRole('button', { name: 'Approve' }).click();
  await app.type('ls -la');
  await app.press('Enter');
  await expect(app).toMatchSemanticSnapshot();
});
`,
    );
  });

  it('wraps actions after a step marker in test.step()', () => {
    const events: RecordedEvent[] = [
      { kind: 'launch', command: ['node', 'app.js'], t: 0 },
      { kind: 'step', title: 'approve', t: 10 },
      { kind: 'click', selector: selector('b1'), t: 20 },
      { kind: 'assert-visible', selector: selector('b2'), t: 30 },
    ];

    expect(generateTestSource(events)).toBe(
      `// Generated by \`termwright ui\` (recorder). Review before committing:
// generated selectors are the narrowest ones the tree allowed, not
// necessarily the ones that describe your intent.

import { expect, test } from '@termwright/test';

test('recorded session', async ({ terminal, step }) => {
  const app = await terminal.launch({ command: ['node', 'app.js'] });

  await step('approve', async () => {
    await app.getByRole('button', { name: 'Approve' }).click();
    await expect(app.getByRole('button', { name: 'Reject' })).toBeVisible();
  });
});
`,
    );
  });

  it('imports only what it uses', () => {
    const source = generateTestSource([
      { kind: 'launch', command: ['ls'], t: 0 },
      { kind: 'press', keys: 'Enter', t: 1 },
    ]);
    expect(source).toContain("import { test } from '@termwright/test';");
    expect(source).not.toContain('expect');
  });

  it('escapes strings it embeds', () => {
    const source = generateTestSource([
      { kind: 'launch', command: ['sh', '-c', "echo 'hi'"], t: 0 },
      { kind: 'type', text: "it's\n", t: 1 },
    ]);
    expect(source).toContain("command: ['sh', '-c', 'echo \\'hi\\'']");
    expect(source).toContain("await app.type('it\\'s\\n');");
  });

  it('writes unrecognised input as raw bytes rather than dropping it', () => {
    const source = generateTestSource([
      { kind: 'launch', command: ['ls'], t: 0 },
      { kind: 'raw', dataB64: 'G1s8MDsxOzFN', t: 1 },
    ]);
    expect(source).toContain("await app.write(Buffer.from('G1s8MDsxOzFN', 'base64'));");
  });

  it('still produces a compilable file when nothing was launched', () => {
    const source = generateTestSource([{ kind: 'press', keys: 'Enter', t: 1 }]);
    expect(source).toContain('const app = await terminal.launch(');
    expect(source).toContain("await app.press('Enter');");
  });

  it('honours a custom variable name', () => {
    const source = generateTestSource([{ kind: 'launch', command: ['ls'], t: 0 }], {
      variable: 'cli',
    });
    expect(source).toContain('const cli = await terminal.launch(');
  });
});
