export const UNICODE_CORPUS = Object.freeze([
  { id: 'ascii', text: 'A', expectedColumns: 1 },
  { id: 'latin-1', text: 'é', expectedColumns: 1 },
  { id: 'combining', text: 'e\u0301', expectedColumns: 1 },
  { id: 'multiple-combining', text: 'a\u0301\u0327', expectedColumns: 1 },
  { id: 'emoji-vs15', text: '❤\uFE0E', expectedColumns: 1 },
  { id: 'emoji-vs16', text: '❤\uFE0F', expectedColumns: 2 },
  { id: 'emoji-skin-tone', text: '👍🏽', expectedColumns: 2 },
  { id: 'emoji-zwj-family', text: '👨‍👩‍👧', expectedColumns: 2 },
  { id: 'emoji-zwj-profession', text: '👩‍💻', expectedColumns: 2 },
  { id: 'emoji-zwj-gender', text: '🏃‍♀️', expectedColumns: 2 },
  { id: 'regional-indicator-flag', text: '🇵🇱', expectedColumns: 2 },
  { id: 'keycap', text: '1️⃣', expectedColumns: 2 },
  {
    id: 'tag-sequence-england',
    text: '🏴\u{E0067}\u{E0062}\u{E0065}\u{E006E}\u{E0067}\u{E007F}',
    expectedColumns: 2,
  },
  { id: 'arabic-marks', text: 'مَرْحَبًا', expectedColumns: 5 },
  { id: 'devanagari-conjunct', text: 'क्ष', expectedColumns: 2 },
  { id: 'devanagari-marks', text: 'किं', expectedColumns: 1 },
  { id: 'hangul-syllable', text: '각', expectedColumns: 2 },
  { id: 'thai-combining', text: 'ก้', expectedColumns: 1 },
  { id: 'mixed-ltr-rtl', text: 'AمB', expectedColumns: 3 },
  { id: 'cjk', text: '世', expectedColumns: 2 },
  { id: 'ambiguous-box', text: '│' },
  { id: 'zero-width-space', text: 'A\u200B', expectedColumns: 1 },
  {
    id: 'leading-zero-width-space',
    text: '\u200B',
    differenceClassification: 'intentional-terminal-profile-difference',
    differenceNote:
      'An orphan zero-width character has no base cell: Ghostty ignores it while xterm preserves a zero-width placeholder cell.',
  },
]);
